[build]
  publish = "ags-immobilier-v44"
  functions = "ags-immobilier-v43/netlify/functions"

[[redirects]]
  from = "/api/biens"
  to = "/.netlify/functions/get-biens"
  status = 200

[[redirects]]
  from = "/api/bien/:id"
  to = "/.netlify/functions/get-bien"
  status = 200
